name: Build and Release

on:
  push:
    paths:
      - 'version.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'  # Updated to the latest stable Go version

      - name: Build Application
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...

      - name: Extract Version
        id: vars
        run: echo "tag=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          release_name: Release ${{ steps.vars.outputs.tag }}
          draft: false
          prerelease: false