name: Build and Release

on:
  push:
    paths:
      - 'version.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Uses the latest major version

      - name: Set Up Go
        uses: actions/setup-go@v3  # Uses the latest major version
        with:
          go-version: '1.20'  # Updated to the latest stable Go version

      - name: Build Application
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...

      - name: Extract Version
        id: vars
        run: echo "version=${{ steps.vars.outputs.tag }}" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          release_name: Release ${{ steps.vars.outputs.tag }}
          draft: false
          prerelease: false
